name: dockboxv4
description: "Flutter project to build an interactive Docker interface"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  flutter_launcher_icons: ^0.14.3
  process_run: ^1.2.4
  window_size: ^0.1.0
  http: ^1.4.0
  fl_chart: ^1.0.0
  system_info2: ^4.0.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - .env
    #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/img/logo.png"
    icon_size: 48
